export * from "./Header";
export * from "./Home";
export * from "./ThemeProvider";
export * from "./Footer";
export * from "./Services";
export * from "./SmallFoot";
export * from "./Contact";
export * from "./Login";
export * from "./Getaccess";